### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by xiaoCong2014** [nl101531/JavaWEB#3]
https://github.com/nl101531/JavaWEB/tree/master/JPA-Demo 这个项目无法运行，麻烦改正。多个类出问题，你编译一下idea就会告诉你哪里错。
比如
cn/mrdear/repository/custom/TCityRepositoryImpl.java

**Comment by nl101531** [comment]
这我整合的时候都跑通的了,我猜想你的Q开头的查询实体没生成吧,参考doc里面的学习记录(四),那个会告诉你怎么生成QueryDSL的实体,另外需要执行sql,所以本地数据库也要导入doc里面的sql.sql文件.

如果还有错误请把错误贴出来哈
