### ISSUE TITLE
SSM-Demo直接运用缺少javax.servlet-api的jar包

### ISSUE THREAD

**Issue by stevenAfh** [nl101531/JavaWEB#4]
可以在pom.xml加一个这个jar

**Comment by AngleblackS** [comment]
项目的jar包都没有

**Comment by stevenAfh** [comment]
jar包本来没有，它是需要通过配置pox.xml （这个例子已经配置好啦就是缺少我上面说的jar包配置），然后去maven仓库下载的。

**Comment by nl101531** [comment]
我用的是IDEA,直接在项目控制那里就可以加上tomcat的包依赖了,所以pom里面没配置,你可以加一下
